version: '2'
services:

  mysql:
    image: mysql:5.7.12
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:0.16.2
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - uploads:/var/www/BookStack/public/uploads
    - storage-uploads:/var/www/BookStack/storage/uploads
    ports:
    - "8080:80"

volumes:
 mysql-data:
 uploads:
 storage-uploads:
